version: '3.9'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
      POSTGRES_USER: db_username
    ports:
      - '5432:5432'
