openapi: 3.0.0
info:
  title: Exchange
  description: Api to manage an exchange app like chat
  version: '0.1'
  
paths:
  /user:
    post:
      operationId: registration
      summary: User registration
      description: User registration
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDTO'
      responses:
        '201':
          description: User created
        '409':
          description: User information conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
      tags:
        - user
  /user/otp-confirmation:
    post:
      operationId: enableUser
      summary: Enable user account
      description: Enable user account
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpDTO'
      responses:
        '200':
          description: Operation successful
        '400':
          description: Wrong otp provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '403':
          description: Otp has expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '409':
          description: Information conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
      tags:
        - user
  /user/otp-resend:
    post:
      operationId: resendOtp
      summary: Resent otp code
      description: Resent otp code
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResentOtpDTO'
      responses:
        '200':
          description: successful operation
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '409':
          description: The user is already active
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
      tags:
        - user

components:
  schemas:
    CreateUserDTO:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        profilePicture:
          type: string
        dateOfBird:
          type: string
        lang:
          type: string
          description: User language
          enum:
            - FR
            - EN
          example: EN
          default: EN
      required:
        - username
        - password
        - email
    ClientError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    OtpDTO:
      type: object
      properties:
        email:
          type: string
        code:
          type: string
      required:
        - email
        - code
    ResentOtpDTO:
      type: object
      properties:
        email:
          type: string
      required:
        - email
